/**
 * ZX-M8XXX - one assembly line, assembled in place (pure, DOM-free).
 *
 * The debugger could patch a byte but not an instruction: to turn `LD A,5` into
 * `LD B,(IX+3)` you had to encode it by hand. This takes what the user typed on
 * a disassembly row and hands back the bytes to write there.
 *
 * It drives the project's own assembler -- the sjasmplus Parser and
 * InstructionEncoder -- rather than a private opcode table, so what the ASM panel
 * accepts is what a row accepts: every operand form, undocumented opcodes, the
 * alternative mnemonics, expressions, `$`, and labels (the caller passes its own
 * symbol map, so `CALL init_screen` works and the row round-trips through itself).
 * It does NOT go through Assembler.assemble(), which resets the symbol table and
 * the VFS -- that would clear the ASM panel's build every time someone edited a
 * row. The encoder is driven directly and the little global state it does touch
 * (dialect switches, error collector) is saved and put back.
 *
 * Two things a whole-file assembler never has to decide:
 *
 *   - **Length.** The new instruction replaces one of a known size. Where an
 *     instruction has more than one encoding, the one that matches the size being
 *     replaced does the least damage -- NOP is $00, but `DD 00` is also a NOP and
 *     is two bytes, so replacing a two-byte instruction with NOP need not leave a
 *     stray byte behind. Candidates are generated by prefixing the redundant
 *     index prefix and then VERIFIED with this project's own disassembler: a
 *     candidate is only used when the disassembler decodes it back to exactly the
 *     same mnemonic at exactly the wanted length. That keeps the rule honest
 *     without a hand-written table of equivalences, and it refuses the cases
 *     where the CPU would do the right thing but the row would not show it
 *     (`DD 3E 05` runs as `LD A,5`, but the disassembler splits it, so it is not
 *     offered). Nothing is ever padded to make it FIT: a shorter instruction
 *     writes its bytes and leaves the rest of the old one where it is.
 *
 *   - **What the row prints is what it reads.** The disassembler writes a hex
 *     byte as `FFh` and sjasmplus needs `0FFh` (a number may not start with a
 *     letter), so the text a row shows would not assemble back. Hex literals that
 *     start with a letter get the leading zero here, unless the same text is a
 *     defined symbol.
 */

import { Parser } from '../sjasmplus/parser.js';
import { InstructionEncoder, DialectOptions } from '../sjasmplus/instructions.js';
import '../sjasmplus/instructions2.js';
import '../sjasmplus/instructions3.js';
import { ErrorCollector } from '../sjasmplus/errors.js';
import { parseExpression } from '../sjasmplus/expression.js';
import { Disassembler } from './disasm.js';

// Data directives this understands. Everything else (ORG, EQU, MACRO, INCBIN...)
// belongs to a source file, not to a row of somebody's memory.
const DIR_BYTES = new Set(['DB', 'DEFB', 'DM', 'DEFM', 'BYTE']);
const DIR_ZTERM = new Set(['DZ']);
const DIR_WORDS = new Set(['DW', 'DEFW', 'WORD']);
const DIR_SPACE = new Set(['DS', 'DEFS', 'BLOCK']);

// Registers and conditions never mean a label, whatever the symbol map says.
const NOT_A_SYMBOL = new Set([
    'A', 'B', 'C', 'D', 'E', 'H', 'L', 'I', 'R', 'F',
    'AF', 'BC', 'DE', 'HL', 'SP', 'PC', 'IX', 'IY',
    'IXH', 'IXL', 'IYH', 'IYL', 'XH', 'XL', 'YH', 'YL', 'HX', 'LX', 'HY', 'LY',
    'NZ', 'Z', 'NC', 'PO', 'PE', 'P', 'M'
]);

// Run fn with the dialect switches on and a private error collector, then put
// back whatever the ASM panel had set. Errors are thrown by ErrorCollector.error,
// so what is collected here is only the warnings and the throw's own record.
function withEncoderEnv(fn) {
    const saved = {
        errors: ErrorCollector.errors,
        warnings: ErrorCollector.warnings,
        errorCount: ErrorCollector.errorCount,
        line: ErrorCollector.currentLine,
        file: ErrorCollector.currentFile,
        alt: DialectOptions.altMnemonics,
        multi: DialectOptions.multiOperand,
        undoc: DialectOptions.undocumented,
        ctx: InstructionEncoder.exprContext
    };
    ErrorCollector.errors = [];
    ErrorCollector.warnings = [];
    ErrorCollector.errorCount = 0;
    ErrorCollector.currentLine = null;
    ErrorCollector.currentFile = null;
    DialectOptions.altMnemonics = true;
    DialectOptions.multiOperand = true;
    DialectOptions.undocumented = true;
    InstructionEncoder.exprContext = null;
    try {
        return fn();
    } finally {
        ErrorCollector.errors = saved.errors;
        ErrorCollector.warnings = saved.warnings;
        ErrorCollector.errorCount = saved.errorCount;
        ErrorCollector.currentLine = saved.line;
        ErrorCollector.currentFile = saved.file;
        DialectOptions.altMnemonics = saved.alt;
        DialectOptions.multiOperand = saved.multi;
        DialectOptions.undocumented = saved.undoc;
        InstructionEncoder.exprContext = saved.ctx;
    }
}

// Apply fn to the parts of the line that are not inside quotes.
function mapUnquoted(text, fn) {
    let out = '';
    let i = 0;
    let plain = '';
    while (i < text.length) {
        const ch = text[i];
        if (ch === '"' || ch === "'") {
            out += fn(plain);
            plain = '';
            let j = i + 1;
            while (j < text.length && text[j] !== ch) {
                if (text[j] === '\\') j++;
                j++;
            }
            out += text.slice(i, Math.min(j + 1, text.length));
            i = j + 1;
            continue;
        }
        plain += ch;
        i++;
    }
    return out + fn(plain);
}

/**
 * `FFh` -> `0FFh`. The disassembler prints hex without a leading zero and the
 * lexer reads a number only when it starts with a digit, so without this the
 * text a row shows cannot be typed back into it. A name that really is a defined
 * symbol (a label called `beefh`) is left alone.
 */
export function normalizeHexLiterals(text, symbols = {}) {
    return mapUnquoted(text, (seg) => seg.replace(
        /\b[A-Fa-f][0-9A-Fa-f]*[hH]\b/g,
        (m) => (Object.prototype.hasOwnProperty.call(symbols, m) ? m : '0' + m)
    ));
}

// A byte source for the disassembler: one instruction's worth of bytes at `base`,
// zero everywhere else, so a decode that runs past the end reports a length that
// cannot match and the candidate is refused.
function bytesMemory(bytes, base) {
    return {
        read(addr) {
            const i = (addr - base) & 0xFFFF;
            return i < bytes.length ? bytes[i] & 0xFF : 0;
        }
    };
}

function decodeAt(bytes, base) {
    return new Disassembler(bytesMemory(bytes, base)).disassemble(base);
}

/**
 * An encoding of the same instruction that is `want` bytes long, or null.
 *
 * The only lengthening the Z80 offers is a redundant DD/FD prefix, which the CPU
 * discards when the opcode behind it has nothing to do with HL. Rather than list
 * which opcodes those are, the candidate is decoded again: if the disassembler
 * gives back the same mnemonic and the whole length, the row will read the same
 * as it did and the prefix is safe to use. (This emulator's DD handler falls
 * through to the unprefixed opcode, so agreeing with the disassembler is also
 * agreeing with the CPU.)
 */
export function altEncoding(bytes, want, address = 0) {
    const extra = want - bytes.length;
    if (extra <= 0) return null;
    const wanted = decodeAt(bytes, address);
    if (!wanted || wanted.length !== bytes.length) return null;
    for (const prefix of [0xDD, 0xFD]) {
        const cand = new Array(extra).fill(prefix).concat(bytes);
        const got = decodeAt(cand, address);
        if (got && got.length === cand.length && got.mnemonic === wanted.mnemonic) return cand;
    }
    return null;
}

// The first operand identifier that is not a register, not a condition and not in
// the symbol map — i.e. the name that made the expression undefined. Only used to
// put a name in the error message.
function firstUnknown(operands, symbols) {
    for (const op of operands) {
        const ids = String(op).match(/[A-Za-z_.][A-Za-z0-9_.]*/g) || [];
        for (const id of ids) {
            if (NOT_A_SYMBOL.has(id.toUpperCase())) continue;
            if (Object.prototype.hasOwnProperty.call(symbols, id)) continue;
            return id;
        }
    }
    return null;
}

function stringBytes(op) {
    const q = op[0];
    if ((q !== '"' && q !== "'") || op.length < 2 || op[op.length - 1] !== q) return null;
    const inner = op.slice(1, -1);
    const out = [];
    for (let i = 0; i < inner.length; i++) out.push(inner.charCodeAt(i) & 0xFF);
    return out;
}

function evalOperand(op, symbols, address) {
    const r = parseExpression(op, symbols, address, null);
    if (!r || r.undefined) return null;
    return r.value | 0;
}

// DB / DZ / DW / DS. Throws an AssemblerError (caught by the caller) on bad input.
function encodeData(directive, operands, address, symbols) {
    const dir = directive.toUpperCase();
    const bytes = [];

    if (DIR_SPACE.has(dir)) {
        if (!operands.length) return { error: `${dir} needs a length` };
        const n = evalOperand(operands[0], symbols, address);
        if (n === null) return { error: `${dir}: unknown symbol` };
        if (n < 0 || n > 4096) return { error: `${dir}: length must be 0-4096` };
        const fill = operands.length > 1 ? evalOperand(operands[1], symbols, address) : 0;
        if (fill === null) return { error: `${dir}: unknown fill value` };
        for (let i = 0; i < n; i++) bytes.push(fill & 0xFF);
        return { bytes };
    }

    if (!operands.length) return { error: `${dir} needs at least one value` };

    for (const op of operands) {
        const text = String(op).trim();
        if (!text) return { error: `${dir}: empty value` };
        const str = stringBytes(text);
        if (str) {
            if (DIR_WORDS.has(dir)) return { error: `${dir} takes numbers, not text` };
            bytes.push(...str);
            continue;
        }
        const v = evalOperand(text, symbols, address);
        if (v === null) return { error: `${dir}: unknown symbol in "${text}"` };
        if (DIR_WORDS.has(dir)) {
            bytes.push(v & 0xFF, (v >> 8) & 0xFF);
        } else {
            if (v < -128 || v > 255) return { error: `${dir}: ${v} does not fit in a byte` };
            bytes.push(v & 0xFF);
        }
    }
    if (DIR_ZTERM.has(dir)) bytes.push(0);
    return { bytes };
}

/**
 * Assemble one line.
 *
 * opts:
 *   address       where the bytes will go (relative jumps and `$` need it)
 *   symbols       { name: value } the operands may use — the debugger's labels
 *   replaceLength the size of the instruction being replaced; when the typed one
 *                 has an encoding of exactly that size, that encoding wins
 *
 * Returns { bytes, label, note } or { error }. `bytes` may be empty (a line that
 * is only a label). `label` is a label the line defined, for the caller to add
 * wherever it keeps them. `note` says when the encoding was chosen for its size.
 */
export function assembleLine(text, opts = {}) {
    const address = (opts.address | 0) & 0xFFFF;
    const symbols = opts.symbols || {};
    const replaceLength = opts.replaceLength || 0;

    const src = String(text == null ? '' : text).trim();
    if (!src) return { error: 'Nothing to assemble' };
    if (/[\r\n]/.test(src)) return { error: 'One instruction per line' };

    return withEncoderEnv(() => {
        let parsed;
        try {
            parsed = Parser.parse(normalizeHexLiterals(src, symbols), '<row>');
        } catch (e) {
            return { error: e.message || String(e) };
        }
        if (!parsed || parsed.length === 0) return { error: 'Nothing to assemble' };
        if (parsed.length > 1) return { error: 'One instruction per line' };

        const line = parsed[0];
        const label = line.label ? String(line.label).replace(/:$/, '') : null;
        let bytes = [];
        let note = '';

        // A label the line defines names the address it is at, so `loop: djnz loop`
        // resolves without the caller having added it first.
        const syms = label ? Object.assign({}, symbols, { [label]: address }) : symbols;

        if (line.directive) {
            const dir = line.directive.toUpperCase();
            if (!DIR_BYTES.has(dir) && !DIR_WORDS.has(dir) &&
                !DIR_SPACE.has(dir) && !DIR_ZTERM.has(dir)) {
                return { error: `${dir} is a source directive, not an instruction` };
            }
            let data;
            try {
                data = encodeData(dir, line.operands, address, syms);
            } catch (e) {
                return { error: e.message || String(e) };
            }
            if (data.error) return { error: data.error };
            bytes = data.bytes;
        } else if (line.instruction) {
            let res;
            try {
                res = InstructionEncoder.encode(line.instruction, line.operands, address, syms);
            } catch (e) {
                return { error: e.message || String(e) };
            }
            if (!res) {
                return { error: `Unknown instruction: ${line.instructionRaw || line.instruction}` };
            }
            if (res.undefined) {
                const name = firstUnknown(line.operands, syms);
                return { error: name ? `Unknown symbol: ${name}` : 'Unknown symbol in operand' };
            }
            // A JR out of range is a warning in the assembler, where a later pass
            // may still move the target. Here there is no later pass, so the bytes
            // would simply be wrong: refuse, and say why.
            if (ErrorCollector.warnings.length) {
                return { error: ErrorCollector.warnings[0].message };
            }
            bytes = res.bytes.map(b => b & 0xFF);

            if (replaceLength && bytes.length < replaceLength) {
                const alt = altEncoding(bytes, replaceLength, address);
                if (alt) {
                    bytes = alt;
                    note = `${replaceLength}-byte encoding used`;
                }
            }
        } else if (!label) {
            return { error: 'Nothing to assemble' };
        }

        return { bytes, label, note };
    });
}
